-- スキーマ（任意）
CREATE SCHEMA IF NOT EXISTS public;

-- 1) 省庁マスタ（organization_name → agency）
CREATE TABLE IF NOT EXISTS agency (
  agency_id       SMALLINT PRIMARY KEY,
  agency_name     VARCHAR(255) NOT NULL,
  agency_order    SMALLINT     CHECK (agency_order >= 0)
);

COMMENT ON TABLE agency IS '日本の府省庁マスタ';
COMMENT ON COLUMN agency.agency_order IS '建制順（小さいほど上位）';

CREATE INDEX IF NOT EXISTS ix_agency_order ON agency (agency_order);

-- 2) 組織（organization）
CREATE TABLE IF NOT EXISTS organization (
  organization_id       SMALLINT PRIMARY KEY,
  supervising_agency_id SMALLINT NOT NULL,
  agency_id             SMALLINT NOT NULL,
  bureau_office         VARCHAR(255),
  division              VARCHAR(255),
  department            VARCHAR(255),
  section               VARCHAR(255),
  team                  VARCHAR(255),
  unit                  VARCHAR(255),

  CONSTRAINT fk_org_supervising_agency
    FOREIGN KEY (supervising_agency_id) REFERENCES agency(agency_id)
      ON UPDATE RESTRICT ON DELETE RESTRICT,

  CONSTRAINT fk_org_agency
    FOREIGN KEY (agency_id) REFERENCES agency(agency_id)
      ON UPDATE RESTRICT ON DELETE RESTRICT
);

COMMENT ON TABLE organization IS '府省庁配下の組織階層';
COMMENT ON COLUMN organization.bureau_office IS '局・庁に相当';

-- （推奨）同一 agency 内の階層重複を防ぐための一意制約
-- NULLを含むと一意にならないため、COALESCEで空文字に寄せる式インデックスを利用
CREATE UNIQUE INDEX IF NOT EXISTS uq_org_unique_path
ON organization (
  agency_id,
  COALESCE(bureau_office, ''),
  COALESCE(division, ''),
  COALESCE(department, ''),
  COALESCE(section, ''),
  COALESCE(team, ''),
  COALESCE(unit, '')
);

-- 3) 事業（project）
CREATE TABLE IF NOT EXISTS project (
  project_id                    SMALLINT   NOT NULL,
  budget_year                   SMALLINT   NOT NULL,
  project_year                  SMALLINT,
  project_name                  VARCHAR(255),
  organization_id               SMALLINT   NOT NULL,
  main_change_reason            VARCHAR(2000),
  notes                         VARCHAR(4000),

  initial_budget_total          NUMERIC(16,2) DEFAULT 0,
  adjustment_total              NUMERIC(16,2) DEFAULT 0,
  carryover_from_previous_total NUMERIC(16,2) DEFAULT 0,
  contingency_total             NUMERIC(16,2) DEFAULT 0,
  execution_total               NUMERIC(16,2) DEFAULT 0,
  carryover_to_next_total       NUMERIC(16,2) DEFAULT 0,
  next_year_request_total       NUMERIC(16,2) DEFAULT 0,

  CONSTRAINT pk_project PRIMARY KEY (project_id, budget_year),

  CONSTRAINT fk_project_organization
    FOREIGN KEY (organization_id) REFERENCES organization(organization_id)
      ON UPDATE RESTRICT ON DELETE RESTRICT,

  CONSTRAINT ck_project_years
    CHECK (
      budget_year  BETWEEN 1990 AND 2100
      AND (project_year IS NULL OR project_year BETWEEN 1990 AND 2100)
    )
);

CREATE INDEX IF NOT EXISTS ix_project_org ON project (organization_id);
CREATE INDEX IF NOT EXISTS ix_project_year ON project (budget_year);

COMMENT ON TABLE project IS '予算事業テーブル（複合PK: project_id + budget_year）';

-- 4) 典型的な結合ビュー（参照しやすい形）
CREATE OR REPLACE VIEW v_project_with_org AS
SELECT
  p.project_id,
  p.budget_year,
  p.project_year,
  p.project_name,
  p.organization_id,
  a.agency_id,
  a.agency_name,
  a.agency_order,
  o.bureau_office, o.division, o.department, o.section, o.team, o.unit,
  p.initial_budget_total, p.adjustment_total, p.carryover_from_previous_total,
  p.contingency_total, p.execution_total, p.carryover_to_next_total, p.next_year_request_total
FROM project p
JOIN organization o ON o.organization_id = p.organization_id
JOIN agency a ON a.agency_id = o.agency_id;


-- 支出先ブロック
CREATE TABLE IF NOT EXISTS project_spending_block (
  block_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id         SMALLINT   NOT NULL,
  budget_year        SMALLINT   NOT NULL,          -- 今回は 2024 を投入
  block_no           VARCHAR(8) NOT NULL,          -- 'A','B',...
  block_name         VARCHAR(255),
  role_in_project    VARCHAR(1000),
  block_total_amount NUMERIC(16,2),
  created_at         TIMESTAMP DEFAULT now(),

  CONSTRAINT fk_psb_project
    FOREIGN KEY (project_id, budget_year)
    REFERENCES project(project_id, budget_year)
      ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_psb_project_block
  ON project_spending_block(project_id, budget_year, block_no);

-- 支出先（企業）
CREATE TABLE IF NOT EXISTS project_spending (
  spending_id            BIGSERIAL PRIMARY KEY,
  block_id               BIGINT    NOT NULL,
  project_id             SMALLINT  NOT NULL,
  budget_year            SMALLINT  NOT NULL,

  recipient_name         VARCHAR(255),
  corporate_number       CHAR(13),                  -- 先頭0を保持
  address                VARCHAR(1000),
  corporation_type       VARCHAR(64),
  is_other_recipient     BOOLEAN,
  amount                 NUMERIC(16,2),
  contract_method        VARCHAR(255),
  contract_method_detail VARCHAR(255),
  bidders_count          INTEGER CHECK (bidders_count IS NULL OR bidders_count >= 0),
  successful_bid_rate    NUMERIC(8,3) CHECK (successful_bid_rate IS NULL OR successful_bid_rate BETWEEN 0 AND 10000),
  single_bid_reason      TEXT,
  is_other_contract      BOOLEAN,
  contract_summary       VARCHAR(2000),
  created_at             TIMESTAMP DEFAULT now(),

  CONSTRAINT fk_ps_block
    FOREIGN KEY (block_id) REFERENCES project_spending_block(block_id)
      ON UPDATE CASCADE ON DELETE CASCADE,

  -- 冗長だが検索しやすいように project も直接参照
  CONSTRAINT fk_ps_project
    FOREIGN KEY (project_id, budget_year)
    REFERENCES project(project_id, budget_year)
      ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_ps_project ON project_spending(project_id, budget_year);
CREATE INDEX IF NOT EXISTS ix_ps_corpno ON project_spending(corporate_number);
CREATE INDEX IF NOT EXISTS ix_ps_method ON project_spending(contract_method);



-- genre table
CREATE TABLE IF NOT EXISTS genre (
  genre_id   BIGSERIAL PRIMARY KEY,
  genre_name VARCHAR(255) NOT NULL UNIQUE
);

-- project_genre table
CREATE TABLE IF NOT EXISTS project_genre (
  project_id    SMALLINT NOT NULL,
  budget_year   SMALLINT NOT NULL,
  genre_id      BIGINT   NOT NULL,

  CONSTRAINT pk_project_genre PRIMARY KEY (project_id, budget_year, genre_id),

  CONSTRAINT fk_pg_project
    FOREIGN KEY (project_id, budget_year) REFERENCES project(project_id, budget_year)
      ON UPDATE RESTRICT ON DELETE RESTRICT,

  CONSTRAINT fk_pg_genre
    FOREIGN KEY (genre_id) REFERENCES genre(genre_id)
      ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- target table
CREATE TABLE IF NOT EXISTS target (
  target_id   BIGSERIAL PRIMARY KEY,
  target_name VARCHAR(255) NOT NULL UNIQUE
);

-- project_target table
CREATE TABLE IF NOT EXISTS project_target (
  project_id    SMALLINT NOT NULL,
  budget_year   SMALLINT NOT NULL,
  target_id     BIGINT   NOT NULL,

  CONSTRAINT pk_project_target PRIMARY KEY (project_id, budget_year, target_id),

  CONSTRAINT fk_pt_project
    FOREIGN KEY (project_id, budget_year) REFERENCES project(project_id, budget_year)
      ON UPDATE RESTRICT ON DELETE RESTRICT,

  CONSTRAINT fk_pt_target
    FOREIGN KEY (target_id) REFERENCES target(target_id)
      ON UPDATE RESTRICT ON DELETE RESTRICT
);

-- region table
CREATE TABLE IF NOT EXISTS region (
  region_id   BIGSERIAL PRIMARY KEY,
  region_name VARCHAR(255) NOT NULL UNIQUE
);

-- project_region table
CREATE TABLE IF NOT EXISTS project_region (
  project_id    SMALLINT NOT NULL,
  budget_year   SMALLINT NOT NULL,
  region_id     BIGINT   NOT NULL,

  CONSTRAINT pk_project_region PRIMARY KEY (project_id, budget_year, region_id),

  CONSTRAINT fk_pr_project
    FOREIGN KEY (project_id, budget_year) REFERENCES project(project_id, budget_year)
      ON UPDATE RESTRICT ON DELETE RESTRICT,

  CONSTRAINT fk_pr_region
    FOREIGN KEY (region_id) REFERENCES region(region_id)
      ON UPDATE RESTRICT ON DELETE RESTRICT
);
